apiVersion: v2
appVersion: jxl-boot-0.0.183-jxlabs.nos.staging.0d3d4ce-dev.327e939-dev+0d3d4ce-dev+0d3d4ce-dev+cbd3e65-dev+0d3d4ce
description: A Helm chart for Kubernetes
icon: https://rawcdn.githack.com/jenkins-x/jx-docs/e9afbc5c933c8f2d004cb041e2fa33b391a8fd23/static/images/logo/jenkinsx-ico-black.png
name: jxl-boot
version: jxl-boot-0.0.183-jxlabs.nos.staging.0d3d4ce-dev.327e939-dev+0d3d4ce-dev+0d3d4ce-dev+cbd3e65-dev+0d3d4ce
